# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='rani bazar', max_length=120),
        ),
    ]
